import os
import json
from groq import Groq

_client = None

def _get_client():
    global _client
    if _client is None:
        _client = Groq(api_key=os.environ["GROQ_API_KEY"])
    return _client

PROMPT_TEMPLATE = """You are assessing whether a piece of text was written by a human or generated by an AI language model.

Score the text on a scale from 0.0 to 1.0, where:
- 1.0 means you are confident a HUMAN wrote this text
- 0.0 means you are confident an AI generated this text
- 0.5 means you are genuinely unsure

Consider voice, specificity, idiosyncrasy, natural imperfection, and contextual coherence.

Respond with ONLY a JSON object in this exact format, nothing else:
{{"score": <float between 0.0 and 1.0>, "reasoning": "<one sentence>"}}

Text to assess:
\"\"\"{text}\"\"\"
"""

def calculate_llm_signal(text: str) -> dict:
    """
    Returns a dict with:
      - llm_score: float in [0.0, 1.0], where 1.0 = confidently human, 0.0 = confidently AI
      - llm_reasoning: short string explanation from the model
    Falls back to a neutral 0.5 score (with an error note) if the API call fails
    or returns unparseable output, so a single signal failure doesn't crash /submit.
    """
    try:
        client = _get_client()
        response = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[{"role": "user", "content": PROMPT_TEMPLATE.format(text=text)}],
            temperature=0.0,
            max_tokens=150,
        )
        raw = response.choices[0].message.content.strip()
        # Strip markdown code fences if the model wraps its JSON in them
        if raw.startswith("```"):
            raw = raw.strip("`")
            if raw.startswith("json"):
                raw = raw[4:]
            raw = raw.strip()
        parsed = json.loads(raw)
        score = float(parsed.get("score", 0.5))
        score = max(0.0, min(1.0, score))  # clamp defensively
        reasoning = str(parsed.get("reasoning", ""))
        return {"llm_score": round(score, 2), "llm_reasoning": reasoning}
    except Exception as e:
        print(f"LLM SIGNAL ERROR: {e}")
        return {"llm_score": 0.5, "llm_reasoning": f"signal_error: {e}"}